#baseURL = "http://localhost:1313/"
baseURL = "https://discipleschool.com/"
languageCode = "en-us"
title = "Disciple School"
theme = "after-dark"
#markup = "markdown"
#description needs to be 50-300 words. Get my description from discipleschool.com
googleAnalytics = "UA-68558525-4"
#disqusShortname = ""
keywords = [
  "bible study",
  "discipling",
  "disciple",
  "disciple school",
  "discipleschool",
  "disciples",
  "discipleship",
  "disciple making",
  "making disciples",
  "true disciples",
  "church",
  "apologetics",
  "evangelism",
  "christianity",
  "jesus",
  "bible",
  "jason west",
  "apostolic",
  "pentecostal"
]

[blackfriday]
  hrefTargetBlank = true

[params]
  author = "Jason West"
  description = "Disciple School will help you become and produce true disciples of Jesus Christ."
  images = [
    "" #set the default image if a post does not have a featured image specified
  ]

[social]
  facebook = "seeksavesend"
  twitter = "seeksavesend"

[params.seo]
  telegram_channel = "discipleschool" # omit the `@`
  disable_bpg = true # Disable BPG image support

[params.seo.webmaster_verifications]
  google = "google33bb9c8df9b14443.html" # Optional, Google verification code
  bing = "EAD018090A1C80C7BCF1D0597504AFCE" # Optional, Bing verification code
  #alexa = "" # Optional, Alexa verification code
  yandex = "d211d986614bd557" # Optional, Yandex verification code

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS", "JSON"]
  #COMMENTED out the above line to remove errors in compiler about NO TEMPLATE existing for JSON content
  #Removed the comment on 01-06-20 with no error

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Posts"
  weight = 2
  identifier = "post"
  url = "/post/"
[[menu.main]]
  name = "Search"
  weight = 3
  identifier = "search"
  url = "/search/"


#[[menu.social]]
#  name = "FB"
#  identifier = "facebook"
#  weight = 1
#  url = "https://www.facebook.com/seeksavesend"
#  pre = "<img src='ico_fb.svg' height='16' width='16'></img>"
#[[menu.social]]
#  name = "T"
#  identifier = "twitter"
#  weight = 2
#  url = "https://twitter.com/seeksavesend"
#  pre = "<img src='twitter_ico.svg' height='16' width='16'></img>"
#[[menu.social]]
#  name = "YT"
#  identifier = "youtube"
#  weight = 3
#  url = "https://www.youtube.com/channel/UCbz86f96_2yeWPyAY6tQgkA"
#  pre = "<img src='youtube.svg' height='16' width='16'></img>"
#[[menu.social]]
#  name = "Instagram"
#  identifier = "instagram"
#  weight = 4
#  url = "https://www.instagram.com/seeksavesend"
#[[menu.social]]
#  name = "Medium"
#  identifier = "medium"
#  weight = 5
#  url = "https://medium.com/@seeksavesend"
#[params.layout.menu.social]
#  hidden = true # set `false` or remove to show section menu
#  exclude = ["instagram", "medium"] # exclude homepage and blog postings


#[[menu.main]]
#  name = "Book Reviews"
#  weight = 3
#  identifier = "books"
#  url = "/books/"
